# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sfs1d <- function(saf, block, num_boot, fold) {
    .Call(`_haplodiplo_sfs1d`, saf, block, num_boot, fold)
}

sfs2d <- function(saf0, saf1, block, num_boot, fold) {
    .Call(`_haplodiplo_sfs2d`, saf0, saf1, block, num_boot, fold)
}

sfs3d <- function(saf0, saf1, saf2, block, num_boot, fold) {
    .Call(`_haplodiplo_sfs3d`, saf0, saf1, saf2, block, num_boot, fold)
}

