# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sfs1d <- function(saf, block, num_boot, fold) {
    .Call(`_haplodiplo_sfs1d`, saf, block, num_boot, fold)
}

sfs2d <- function(saf0, saf1, block, num_boot, fold) {
    .Call(`_haplodiplo_sfs2d`, saf0, saf1, block, num_boot, fold)
}

sfs3d <- function(saf0, saf1, saf2, block, num_boot, fold) {
    .Call(`_haplodiplo_sfs3d`, saf0, saf1, saf2, block, num_boot, fold)
}

FST <- function(saf0, saf1, sfs) {
    .Call(`_haplodiplo_FST`, saf0, saf1, sfs)
}

theta <- function(saf, sfs) {
    .Call(`_haplodiplo_theta`, saf, sfs)
}

slider <- function(inp, coord, window, step) {
    .Call(`_haplodiplo_slider`, inp, coord, window, step)
}

hfs1d <- function(shf, cfg, block, num_boot, proj) {
    .Call(`_haplodiplo_hfs1d`, shf, cfg, block, num_boot, proj)
}

